services:

  backend:
    build:
      context: ./backend
    restart: always
    container_name: backend
    ports:
      - "3000:3000"
  
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"